### ISSUE TITLE
Failed to deploy UUPS on Windows

### ISSUE THREAD

**Issue by nufailTanjiro** [OpenZeppelin/openzeppelin-foundry-upgrades#54]
When I run 
```bash
forge script --chain sepolia script/DeployDeedX.sol:DeployDeedX --rpc-url $SEPOLIA_RPC_URL --broadcast --verify -vvvv
```

I am getting an error saying:
![image](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/assets/146712412/0d3f57f6-0685-4d6b-be9f-ff395ae7994a)

I addedon my .env:
```bash
OPENZEPPELIN_BASH_PATH="C:/Program Files/Git/bin/bash"
```

* my Script:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Script.sol";
import {DeedX} from "../src/DeedX.sol";
import {Upgrades} from "openzeppelin-foundry-upgrades/Upgrades.sol";

contract DeployDeedX is Script {
    function run() external {
        vm.startBroadcast();
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");

        address proxy = Upgrades.deployUUPSProxy("DeedX.sol", abi.encodeCall(DeedX.initialize, ()));

        vm.stopBroadcast();
    }
}

```

**Comment by nufailTanjiro** [comment]
Hi @ericglau 
* I am using WSL2
* I am getting ```-bash: C:/Program Files/Git/bin/bash: No such file or directory```
* I am getting ```bash: C:/Program Files/Git/bin/bash: No such file or directory```

![image](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/assets/146712412/27c38ed2-baa2-47bc-b5af-742c54899366)
![image](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/assets/146712412/0e4aef22-2078-483a-aa44-6688e14a37c3)

**Comment by ericglau** [comment]
Do you have the bash executable available at `C:/Program Files/Git/bin/bash`? Can you ensure that `OPENZEPPELIN_BASH_PATH` is set to a path that contains the `bash` executable?

You could try installing [Git for Windows](https://gitforwindows.org/) if needed.

**Comment by nufailTanjiro** [comment]
The bash executable file is in `C:/Program Files/Git/bin/bash`:

![image](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/assets/146712412/abb29c2e-e124-4333-8be1-f6cb6f049579)


I have also added in my environment variable:
![image](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/assets/146712412/2abf9ecd-1cf5-44e8-bd89-7c6990aa055e)

**Comment by nufailTanjiro** [comment]
When I execute this command `"C:/Program Files/Git/bin/bash" "--version"` on my Windows command prompt I got the version and bash details. But when I execute in my WSL cmd I get `-bash: C:/Program Files/Git/bin/bash: No such file or directory`

**Comment by ericglau** [comment]
Can you try running the forge script from the Windows command prompt (not WSL)?  Or, change `OPENZEPPELIN_BASH_PATH` to the bash directory within WSL (using Linux-style paths)?

**Comment by nufailTanjiro** [comment]
> * "C:/Program Files/Git/bin/bash" "--version"

This one is solved, Now I'm facing a different issue when running:
```bash 
forge script --chain sepolia script/DeployDeedX.sol:DeployDeedX --rpc-url $SEPOLIA_RPC_URL --broadcast --verify -vvvv```

![image](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/assets/146712412/9ee8560c-3688-417f-9cca-4938d81d9926)

**Comment by ericglau** [comment]
This should be fixed if you update Foundry.  See https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/51#issuecomment-2101741657

**Comment by nufailTanjiro** [comment]
This is my foundry version after running `foundryup`:
```bash
$ forge --version
forge 0.2.0 (f479e94 2024-06-01T00:21:09.122773900Z)
```

I am still getting the same error

**Comment by nufailTanjiro** [comment]
![image](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/assets/146712412/a9b516d1-5958-402e-9a87-3fa1e13efd3c)
This is my error

**Comment by ericglau** [comment]
- Can you share how you fixed the original issue with the bash path, and what is the current value of `OPENZEPPELIN_BASH_PATH`?
- How are you running the Forge script, is it from Windows Command Line or WSL?
- Would you be able to share the .json file(s) from the `out/build-info` subdirectory of your project so that I can look into the issue further? Note that this file contains all of your contracts' source code.

**Comment by ericglau** [comment]
Looks like the zip file link isn't working, can you try uploading it again?

**Comment by ericglau** [comment]
Thanks, I was able to access that.  It looks like there may be some conflicts in your remappings.  Some of the dependencies are referencing paths such as `node_modules/@openzeppelin/contracts-upgradeable` while some are referencing `lib/openzeppelin-contracts-upgradeable`

It looks like you are using npm modules (`node_modules`) for the OpenZeppelin Contracts dependencies.  If this is the intention, could you try updating your `remappings.txt` to use those exclusively, for example:
```
@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/
@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/
```

If this does not resolve the issue, would you be able to share your repository or a minimal reproducible repository with the way that your project is set up?

**Comment by nufailTanjiro** [comment]
I changed the `remappings.txt` but not resolved.

Here is the repo link: 
https://github.com/codinglegendsdevs/deedx-contracts

**Comment by ericglau** [comment]
I'm not able to access that repo, can you grant me access?  Thanks for your patience with this.

**Comment by nufailTanjiro** [comment]
Sorry my bad, I've given you access now

**Comment by ericglau** [comment]
Thanks. I tried the following with your repo:
1. Changed `remappings.txt` to match my [previous comment](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/54#issuecomment-2148277350)
2. Ran the script locally using: `forge script script/DeployDeedX.sol --force`
3. This was able to progress to run upgrade safety validations, which failed with the following error because it looks like the variable is missing a `constant` keyword.
```
script failed: revert: Upgrade safety validation failed:
✘  src/DeedX.sol:DeedX

      src/DeedX.sol:25: Variable `DEEDX_GOVERNANCE` is assigned an initial value
          Move the assignment to the initializer
          https://zpl.in/upgrades/error-004
```

If you are still getting the error from https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/54#issuecomment-2144399825, ensure you are using `--force` when running `forge script`.

I'll see if I can try the above on Windows as well.

**Comment by ericglau** [comment]
It looks like this is because you are running deployment on sepolia but the broadcast is not set up correctly.
In your script you have
```
        vm.startBroadcast();
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
```
but it should be
```
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);
```

Also, minor suggestion with your implementation, I think for your `DEEDX_GOVERNANCE` role, you could just make it a constant if the hash doesn't need to be changed:
```
bytes32 public constant DEEDX_GOVERNANCE = keccak256("DEEDX_GOVERNANCE");
```

**Comment by nufailTanjiro** [comment]
Thanks, it worked. 
By the way, facing an issue when verifying the contract

```bash
forge script --chain 80002 script/DeployDeedX.sol:DeployDeedX --rpc-url $POLYGON_AMOYNET_RPC --broadcast --verify -vvvv --force
```
This command successfully deployed the contract but failed to verify since I am deploying and verifying using polygon amoy

So to verify it manually, after the deployment I ran:
```bash
forge  verify-contract --compiler-version 0.8.20 --chain polygon-amoy  0x9E17cFc7AA8A067818381d8CAd35cf1AA6C1e623 src/DeedX.sol:DeedX  --verifier-url $AMOY_POLYGON_VERIFIER_URL --etherscan-api-key $POLYGON_SCAN_API_KEY
```

The console returned success:
```bash
Start verifying contract `0x9E17cFc7AA8A067818381d8CAd35cf1AA6C1e623` deployed on amoy

Submitting verification for [src/DeedX.sol:DeedX] 0x9E17cFc7AA8A067818381d8CAd35cf1AA6C1e623.
Submitted contract for verification:
        Response: `OK`
        GUID: `u2nec45ryd8kwd7gfyd81eqtpshmmul75cm6clfmwvrz1qt9gm`
        URL: https://amoy.polygonscan.com/address/0x9e17cfc7aa8a067818381d8cad35cf1aa6c1e623

```

But when I visit the amoy.polygonsacan URL, the contract not verified:
* [Implementation contract on amoy.polgonscan](https://amoy.polygonscan.com/address/0x9e17cfc7aa8a067818381d8cad35cf1aa6c1e623#code)

**Comment by nufailTanjiro** [comment]
This is what I have on my foundry.toml:
```toml

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
polygon-amoy = "${POLYGON_AMOYNET_RPC}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon-amoy = { key = "${POLYGON_SCAN_API_KEY}" }
```

**Comment by ericglau** [comment]
I don't think I can help much as that might be a block explorer issue.  But I would suggest getting your build-info file from `out/build-info`, extract the `input` section's contents into a standalone JSON file, for example from
```
{
  "_format": "ethers-rs-sol-build-info-1",
  "solcVersion": "0.8.26",
  "solcLongVersion": "0.8.26",
  "input": {
    "language": "Solidity",
    "sources": {
      ...
    },
    "settings": {
      ...
    }
  },
...
```
to
```
{
    "language": "Solidity",
    "sources": {
      ...
    },
    "settings": {
      ...
    }
}
```
Then use that new file as the Solc JSON input to manually verify on the block explorer.  See https://forum.openzeppelin.com/t/how-to-verify-a-contract-on-etherscan-bscscan-polygonscan/14225 for some general info on verification.

**Comment by ericglau** [comment]
Closing this issue as it looks like the original problem is resolved.  If you have further issues, feel free to post on https://forum.openzeppelin.com/c/support/upgrades or open another issue as needed.
